# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Burying_Laterals
                                 A QGIS plugin
  This plugin adds lateral and prints a recommended elevation and Distance along the mainlines.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-01-12
        copyright            : (C) 2021 by FALASY Anamelechi
        email                : fvw.services@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Burying_Laterals class from file Burying_Laterals.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Burying_Laterals import Burying_Laterals
    return Burying_Laterals(iface)
